### PR TITLE
Modify 'Header Search Path' for native iOS app to integrate react-nat…

### PR DESCRIPTION
**Pull request by OceanHorn**
Modify 'Header Search Path' for native iOS app to integrate react-native-webp from react-native package.json.

```
In file included from /Users/OceanHorn/SourceTree/mmms/node_modules/react-native-webp/DBAWebpImageDecoder.m:1:
In file included from /Users/OceanHorn/SourceTree/mmms/node_modules/react-native-webp/DBAWebpImageDecoder.h:1:
../../node_modules/react-native/Libraries/Image/RCTImageLoader.h:12:9: fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

### CODE REVIEW

**Comment by sgeier** [comment]
I also tried to apply this fix but I cannot get this to run again with RN 0.60+. I tried on 0.62.4 (after upgrade) and had it all working on 0.59.10. 

Then things stopped working. The exact same issue persists even with a clean 0.62.4 installation.

**Comment by sgeier** [comment]
I found another solution in the meaning time: Using react-native-fast-image for local images.

https://github.com/DylanVann/react-native-fast-image/issues/476#issuecomment-512723403
